---
remotes:
  primary: git@github.com:destructuring/tvdinner
  secondary: git@destructuring.org:destructuring/tvdinner
  rb: https://github.com/destructuring/rb-helper
  bump: https://github.com/destructuring/mixin-bump
