---
remotes:
  primary: git@github.com:destructuring/rb-helper
  secondary: git@destructuring.org:destructuring/rb-helper
  sh: https://github.com/destructuring/jason
  bump: https://github.com/destructuring/mixin-bump
